#pragma once

#include <pebble.h>

#define POKEMON_TILES_PER_SPRITE 4
#define POKEMON_SPRITES_PER_TRAINER 6
#define POKEMON_TRAINER_STAND_DOWN 0
#define POKEMON_TRAINER_STAND_UP 1
#define POKEMON_TRAINER_STAND_LEFT 2
#define POKEMON_TRAINER_STAND_RIGHT 2
#define POKEMON_TRAINER_WALK_DOWN 3
#define POKEMON_TRAINER_WALK_UP 4
#define POKEMON_TRAINER_WALK_LEFT 5
#define POKEMON_TRAINER_WALK_RIGHT 5

#define POKEMON_SPRITE_CUT_TREE 133
#define POKEMON_SPRITE_ITEM 132
#define POKEMON_SPRITELET_GRASS 134 // Only one tile!

const uint8_t pokemon_trainer_sprite_offsets[] = {
    POKEMON_TRAINER_STAND_UP,
    POKEMON_TRAINER_STAND_LEFT,
    POKEMON_TRAINER_STAND_DOWN,
    POKEMON_TRAINER_STAND_RIGHT,
    POKEMON_TRAINER_WALK_UP,
    POKEMON_TRAINER_WALK_LEFT,
    POKEMON_TRAINER_WALK_DOWN,
    POKEMON_TRAINER_WALK_RIGHT,
};

uint8_t pokemon_trainer_palettes[][4] = {
    {1, 1, 0, 0},    // Chris
};