#pragma once

#include <pebble.h>
#include "objects.h"

typedef enum {
    WALKABLE,
    GRASS,
    BLOCKING
} PokemonSquareInfo;

const uint8_t screen[] = {
    P_T_T, P_C_W, P_GRS, P_GRS, P_DRT, P_GRS, P_GRS, P_C_E, P_T_T,
    P_T_B, P_C_W, P_GRS, P_GRS, P_DRT, P_GRS, P_GRS, P_C_E, P_T_B,
    P_T_T, P_CSW, P_C_S, P_C_S, P_C_S, P_C_S, P_C_S, P_CSE, P_T_T,
    P_T_B, P_TGR, P_TGR, P_TGR, P_DRT, P_TGR, P_TGR, P_TGR, P_T_B,
    P_T_T, P_TGR, P_TGR, P_TGR, P_DRT, P_TGR, P_TGR, P_TGR, P_T_T,
    P_T_B, P_TGR, P_TGR, P_TGR, P_DRT, P_TGR, P_TGR, P_TGR, P_T_B,
    P_T_T, P_TGR, P_TGR, P_TGR, P_DRT, P_TGR, P_TGR, P_TGR, P_T_T,
    P_T_B, P_TGR, P_TGR, P_TGR, P_DRT, P_TGR, P_TGR, P_TGR, P_T_B,
    P_T_T, P_TGR, P_TGR, P_TGR, P_DRT, P_TGR, P_TGR, P_TGR, P_T_T,
    P_T_B, P_SHR, P_SHR, P_SHR, P_SHR, P_SHR, P_SHR, P_SHR, P_T_B,
    P_T_T, P_T_T, P_T_T, P_T_T, P_T_T, P_T_T, P_T_T, P_T_T, P_T_T,
};

const uint8_t screen_info[] = {
    BLOCKING, BLOCKING, WALKABLE, WALKABLE, WALKABLE, WALKABLE, WALKABLE, BLOCKING, BLOCKING,
    BLOCKING, BLOCKING, WALKABLE, WALKABLE, WALKABLE, WALKABLE, WALKABLE, BLOCKING, BLOCKING,
    BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING,
    BLOCKING, GRASS   , GRASS   , GRASS   , WALKABLE, GRASS   , GRASS   , GRASS   , BLOCKING,
    BLOCKING, GRASS   , GRASS   , GRASS   , WALKABLE, GRASS   , GRASS   , GRASS   , BLOCKING,
    BLOCKING, GRASS   , GRASS   , GRASS   , WALKABLE, GRASS   , GRASS   , GRASS   , BLOCKING,
    BLOCKING, GRASS   , GRASS   , GRASS   , WALKABLE, GRASS   , GRASS   , GRASS   , BLOCKING,
    BLOCKING, GRASS   , GRASS   , GRASS   , WALKABLE, GRASS   , GRASS   , GRASS   , BLOCKING,
    BLOCKING, GRASS   , GRASS   , GRASS   , WALKABLE, GRASS   , GRASS   , GRASS   , BLOCKING,
    BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING,
    BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING, BLOCKING,
};